libpdbg/bmcfsi.c
We can't build against ulibc with this. Luckily we don't use it, so
remove the include.
Signed-off-by: Joel Stanley <joel@jms.id.au>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/pdbg/2)
=> libpdbg/bmcfsi: argp.h is unused

README.md
The README doesn't look great in markdown, so wrap the examples in code blocks, with a newline separating command and output.
Signed-off-by: Russell Currey <ruscur@russell.cc>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/pdbg/6)
=> Make the README prettier

libpdbg/bmcfsi.c
Putting CRC error messages into stderr helps with scripting that parses
the output of pdbg.
Signed-off-by: Xo Wang <xow@google.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/pdbg/11)
=> bmcfsi: Report read response CRC errors to stderr

libpdbg/bmcfsi.c
Update pin assignments for the board revision that replaces all current
Zaius boards.
The schematic indicates pins G0 and G1 for clock and data but contains
an error that forced rework for all EVT2 and EVT3 boards to use C3 and
C2 for FSI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/pdbg/13)
=> libpdbg/bmcfsi: Update Zaius pin assignments for EVT2

libpdbg/bmcfsi.c, libpdbg/kernel.c
Modified the computing of OpenFSI CFAM address masking
for putcfam and getcfam.
Signed-off-by: Dinesh Chinari <chinari@us.ibm.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/pdbg/16)
=> Fix CFAM address computing for OpenFSI.

libpdbg/chip.c
Fixes: #24 
Signed-off-by: Cyril Bur <cyrilbur@gmail.com>
=> libpdbg: Fix incorrect restore of r1 in ram_instructions()

src/thread.c
endian.h is needed for be64oh otherwise build with musl fails on:
src/thread.c: In function 'flip_endian':
src/thread.c:49:9: error: implicit declaration of function 'be64toh' [-Werror=implicit-function-declaration]
return be64toh(v);
Fixes:
- http://autobuild.buildroot.org/results/81b1107bdb06250e1a7837506aec0c9762e771c5
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
=> src/thread.c: include endian.h

libpdbg/sbe_api.c
Curently sbe_get_state api returns SBE_STATE_NOT_USABLE
incase SBE booted bit is not set. This api should return
the current value of SBE status register to align the BMC
sbe state management design direction. Like BMC sets SBE
state to SBE_STATE_CHECK_CFAM when chassis power is on and
based on the sbe message register status this get updated.
Here it is forcing to unusable state and it is causing
issue in SBE state management.
Tested: Successfully verified in BMC Driver verification test
=> libpdbg: fix sbe_get_state return value

libpdbg/sbefifo.c
Incase chip-op failure pdbg captures last chip-op FFDC information. 
Currently sbefifo back-end mode to get thread status, pdbg makes 
another chip-op. This will override the actual error.
This commits helps to return correct return code for thread start/stop/sreset
chip-ops by skipping thread status update call during failure.
=> libpdbg: skip thread state updates during chipop failure

Makefile.am, libpdbg/device.c, libpdbg/dtb.c, libpdbg/libpdbg.h, libpdbg/target.c, libpdbg/target.h, src/tests/libpdbg_release_dt_root_test.c
Context: It is now required that the devtree backend in BMC systems should be able to switch in the same process on runtime e.g.; from KERNEL to SBEFIFO or vice-versa. This is to support running extract SBE RC hardware procedure. This commit introduces the necessary changes in order to achieve that.
Solution: It basically introduces few functions which will clear the pdbg_dt_root and its associated children subsequently if the pdbg_targets_init function is called more than once now (earlier it was not allowed to call pdbg_targets_init function twice in the same process)
Test-1: The switching of the backend in the same process was tested through a standalone application which runs in a loop for multiple times and each time it sets the intial backend to SBEFIFO first and then switched it to …
=> Adding helper functions for switching of devtree backend in the same process

libpdbg/ocmb.c
Tested
before
{
"MANUAL_ISOLATION": {
"CURRENT_STATE": "DECONFIGURED",
"LOCATION_CODE": "Ufcs-P0-C17",
"PHYS_PATH": "physical:sys-0/node-0/ocmb_chip-9",
"REASON_DESCRIPTION": "MANUAL",
"TYPE": "SBE FIFO Chip-op based OCMB"
}
after
{
"MANUAL_ISOLATION": {
"CURRENT_STATE": "DECONFIGURED",
"LOCATION_CODE": "Ufcs-P0-C17",
"PHYS_PATH": "physical:sys-0/node-0/ocmb_chip-9",
"REASON_DESCRIPTION": "MANUAL",
"TYPE": "OCMB"
}
Change-Id: I4b7eb25a76968a435b78db858923b8a068ca225b
=> OCMB target type renamed to "OCMB"

libpdbg/dtb.c, libpdbg/p10_fapi_targets.c, libpdbg/p10_scom_addr.h, libpdbg/target.c, libpdbg/target.h
Added the translation required for the odyssey chipunit like memport. With this change, the getscom and the putscom support for odyssey chipunits shall work as expected.
Tested and Working as expected.
=> Add getscom support for odyssey chipunit

libpdbg/libpdbg_sbe.h, libpdbg/sbe_api.c, libpdbg/target.c
1) Provide methods to read odyssey sbe state
2) User odyssey fsi target to read the sbe state
Tested:
PDBG:fsi_ody_read[382]: rc = 0, addr = 0x02986, data = 0x00000000, target = /hmfsi-ody@310 sbe state value is 0
Change-Id: I59aa51a90bc235b989e65c937a7ed9b7d2e40a57
=> cater for get and set sbe odyssey state

libpdbg/dtb.c
The expectation was that the /proc/device-tree/model file would precisely indicate the system model, such as Rainier 2u, Rainier 4U, or Everest. Previously, we relied on exact matching of the entire string pattern to load the corresponding Odyssey dtb files. However, in some test systems, additional characters caused the existing conditions to fail, resulting in misidentification as a DDR4 system. To address this issue, the code was modified to search for substrings instead of exact matches. This enabled the code to function as intended.
The ecmdquery chips were tested, successfully probing and loading the necessary Odyssey backend targets
=> Look for Rainier or Everest substring in Model

libpdbg/hwunit.h, libpdbg/p10_fapi_targets.c
OCC is not in hardware unit list as it is not guardable. But, when a proc is guarded OCC is deconfigured by association. Currently we are not seeing OCC in Nag Dump because of unavailable properties like "name" and "class". So, Adding OCC to hardware unit list.
Test Results:
Before:
OCC was not showing up in Nag Dump.
After:
```
root@p10bmc:/tmp/test# faultlog -f
<6> faultlog app to collect deconfig/guard records details <6> Latest chassis poweron time read is :03/20/2024 15:33:49 [
{
"SYSTEM": {
"SYSTEM_TYPE": "9105-42A"
}
},
{
"POLICY": {
"FCO_VALUE": 0,
"MASTER": true,
"PREDICTIVE": true
}
},
{
"MANUAL_ISOLATION": {
"CURRENT_STATE": "DECONFIGURED",
"LOCATION_CODE": "Ufcs-P0-C15",
"PHYS_PATH": "physical:sys-0/node-0/proc-1",
"REASON_DESCRIPTION": "MANUAL",
"TYPE": "Processor Module"
} …
```
=> libpdbg: Add On Chip Controller (OCC) hardware unit

bmc-kernel-everest.dts.m4, bmc-sbefifo-everest.dts.m4
putscom on odyssey -p89 called out the wrong location code, as the device path mapping for ocmb_chip-30 and ocmb_chip-31 were interchanged. This happens only on Everest system. Fixed it both for kernel and sbefifo path.
Tested and working as expected.
=> Fix the device path mapping for Everest

libpdbg/sbefifo.c, libsbefifo/ffdc.c, libsbefifo/operation.c
1) Modify sbe chip-op operation to read FFDC data for chip-op success case so as to get FFDC data from SBE for any earlier or internal SBE failure
2) As SBE now caters for multiple FFDC packets increase the size of the memory allocated by pdbg to read the FFDC data to 32KB.
=> POZ: To cater for additional requirements to parse SBE FFDC data

bmc-kernel-everest.dts.m4, bmc-kernel-rainier.dts.m4, bmc-sbefifo-everest.dts.m4, bmc-sbefifo-rainier.dts.m4, libpdbg/ocmb.c, libpdbg/target.c
The ocmb index value is currently the same as that of the OMI index. This number is not unique and it is not easy to map the index number with the inventory path of the dimm. So using the number at the end of the physical path as the index
=> Fix ocmb index value

libpdbg/sbe_api.c
Revert change done to avoid double memory allocation for ffdc data.
Earlier test was done with single proc which worked as expected but with multiple proc and multiple fork processes trying to read the ffdc data it is causing double free error and core dump.
Tested:
root@p10bmc:/tmp# busctl tree xyz.openbmc_project.Dump.Manager `- /xyz
`- /xyz/openbmc_project
`- /xyz/openbmc_project/dump
|- /xyz/openbmc_project/dump/hostboot
| `- /xyz/openbmc_project/dump/hostboot/entry
|   |- /xyz/openbmc_project/dump/hostboot/entry/20000001
|   |- /xyz/openbmc_project/dump/hostboot/entry/20000002
|   |- /xyz/openbmc_project/dump/hostboot/entry/20000003
Change-Id: If38be58d9938b476ab39f35e69583fda28522cd4
=> POZ : revert avoid double memory allocation for ffdc data

libpdbg/dtb.c
Fixing CI error Conditional jump or move depends on uninitialised value
=> Fix CI error: Conditional jump based on undefined value

libpdbg/dtb.c
In contains_substring_ignoring_case, if the string that we are looking for is longer than the source string, return with string not found. Earlier the char array index went out of bounds due to invalid arthimetic operation on the index.
Tested and found the method working as expected.
=> Fix corner case

libpdbg/ocmb.c
The index values of pdbg targets are updated to match the physical device path. So using the index value for getting the scoms shall fail. The fapi position is still connected to the OMI index. So using the fapi position to calculate the instance id in case of DDR4 system.
root@p10bmc:/tmp# getscom explorer 08012400 -all
explorer        k0:n0:s0:p00       0x0000000000000000
explorer        k0:n0:s0:p01       0x0000000000000000
explorer        k0:n0:s0:p24       0x0000000000000000
explorer        k0:n0:s0:p25       0x0000000000000000
explorer        k0:n0:s0:p32       0x0000000000000000
explorer        k0:n0:s0:p33       0x0000000000000000
explorer        k0:n0:s0:p56       0x0000000000000000
explorer        k0:n0:s0:p57       0x0000000000000000
/usr/bin/edbg getscom explorer 08012400 -all …
=> Fix getscom on DDR4 everst system

libpdbg/p10_fapi_targets.c
Currently we see POWER10 prefix for all targets in Nag Dump for power11
systems, changing it to POWER to make it consistent.
Test Results:
Before:
root@p10bmc:/tmp/test# faultlog -f
<6> faultlog app to collect deconfig/guard records details <6> Latest chassis poweron time read is :02/09/2025 08:08:25 [
{
"SYSTEM": {
"SYSTEM_SN": "139F210",
"SYSTEM_TYPE": "9105-22B"
}
},
{
"POLICY": {
"FCO_VALUE": 4,
"MASTER": true,
"PREDICTIVE": true
}
},
{
"MANUAL_ISOLATION": {
"CURRENT_STATE": "DECONFIGURED",
"LOCATION_CODE": "Ufcs-P0-C27",
"PHYS_PATH": "physical:sys-0/node-0/dimm-4",
"REASON_DESCRIPTION": "MANUAL",
"TYPE": "POWER10 DIMM"     ---> POWER10 prefix
}
},
After:
root@p10bmc:/tmp/test# faultlog -f
<6> faultlog app to collect deconfig/guard records details <6> Latest chassis poweron time read …
=> libpdbg: Replace POWER10 with POWER

libpdbg/htm.c, libpdbg/p10chip.c
For POWER11 systems, NagDump contained POWER10 prefix for all the targets. The prefix was updated to POWER for fapi targets in earlier commit but chip targets and htm targets were missed. Modifying the prefix for core, thread and htm targets to maintain consistency.
Test Results:
Before:
```
{
"MANUAL_ISOLATION": {
"CURRENT_STATE": "DECONFIGURED",
"LOCATION_CODE": "Ufcs-P0-C15",
"PHYS_PATH": "physical:sys-0/node-0/proc-1/eq-0/fc-1/core-1",
"REASON_DESCRIPTION": "MANUAL",
"TYPE": "POWER10 Core"
}
```
After:
```
{
"MANUAL_ISOLATION": {
"CURRENT_STATE": "DECONFIGURED",
"LOCATION_CODE": "Ufcs-P0-C15",
"PHYS_PATH": "physical:sys-0/node-0/proc-1/eq-0/fc-1/core-1",
"REASON_DESCRIPTION": "MANUAL",
"TYPE": "POWER Core"
}
```
Change-Id: If4180988f2bd6417ed1e8b67ef8e5000e4bee8b5
=> libpdbg: Replace POWER10 with POWER for core, thread and htm
